Traceback (most recent call last):
  File "C:\Users\ttamarz\OneDrive - Bank Negara Malaysia\RLMS\qc_template\stats_qc.py", line 373, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\ttamarz\OneDrive - Bank Negara Malaysia\RLMS\qc_template\stats_qc.py", line 358, in main
    alerts = build_flags(df, thr)
  File "C:\Users\ttamarz\OneDrive - Bank Negara Malaysia\RLMS\qc_template\stats_qc.py", line 113, in build_flags
    df[c] = to_num(df[c])
            ~~~~~~^^^^^^^
  File "C:\Users\ttamarz\OneDrive - Bank Negara Malaysia\RLMS\qc_template\stats_qc.py", line 108, in to_num
    def to_num(s): return pd.to_numeric(s, errors="coerce")
                          ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttamarz\AppData\Roaming\Python\Python313\site-packages\pandas\core\tools\numeric.py", line 209, in to_numeric
    raise TypeError("arg must be a list, tuple, 1-d array, or Series")
TypeError: arg must be a list, tuple, 1-d array, or Series
